PLATFORM ?= CWLITEARM
CRYPTO_TARGET ?= NONE
SS_VER ?= SS_VER_2_1

ACTIVATION ?= relu
TARGET = nn-mnist-$(ACTIVATION)

SRC += nn-mnist.c
SRC += nn.c
SRC += model_data_$(ACTIVATION).c

EXTRAINCDIRS += .

EXPERIMENT ?= 0
EXP_RELU_REPEAT ?= 32
EXP_RELU_WIN_START ?= 24
EXP_RELU_WIN_STOP ?= 40

CFLAGS += -DEXPERIMENT=$(EXPERIMENT)
CFLAGS += -DEXP_RELU_REPEAT=$(EXP_RELU_REPEAT)
CFLAGS += -DEXP_RELU_WIN_START=$(EXP_RELU_WIN_START)
CFLAGS += -DEXP_RELU_WIN_STOP=$(EXP_RELU_WIN_STOP)

FIRMWAREPATH = ..

include ../Makefile.inc
